### PR TITLE
optimizations

### PR DESCRIPTION
**Pull request by haarg**
This optimizes the code somewhat.  Some variables are replaced with constants.  Modules are mostly lazy loaded, since usually only one of the routines in the module will be used per process.  The directory creation and file comparisons have also been optimized for their common cases.

Also incorporates the changes in #6.

### CODE REVIEW

**Comment by dolmen** [comment]
@Leont About constant: https://metacpan.org/pod/constant::tiny#Rationale

**Comment by bulk88** [comment]
Personally I never convert code that runs exactly ONCE per perl process lifetime to use constant folding. Perl 5 constant folding runs the code to constant fold it. There is overhead with doing that. It has to be a loop or a public API sub that has some plausible rational on why it would be run more than once per process to use const subs/constant fold it.

**Comment by haarg** [comment]
Half of the OS checks are inside loops.  The others could be changed to just $^O checks, since they should only happen once per process anyway.

**Comment by dolmen** [comment]
Reviewed.
:+1: for merge, with or without the "operating systems should be constants" patch.

**Comment by demerphq** [comment]
Ive comment on most of the commits in this patch sequence. Some I am ok with. Some i think need comment updates and a few are IMO a bit questionable one way or another.

Having said that I am ok with the spririt and intent of this patch sequence.

**Comment by mohawk2** [comment]
Is this PR still desirable? It'll need rebasing because of conflicts.

**Comment by haarg** [comment]
I've rebased this. A number of the changes that were in this PR were already merged.

I do think this is generally a good set of changes, although I haven't verified that it works properly on VMS.

**Comment by haarg** [comment]
I've created #29, #30, and #31 to address the comments here, and be more conservative with the changes.

**Pull request closed without merging**
