### PR TITLE
Rtc 132152 no meta in manifest

### PR DESCRIPTION
**Pull request by jkeenan**
For: https://rt.cpan.org/Ticket/Display.html?id=132152

### CODE REVIEW

**Comment by mohawk2** [comment]
Also looks good to me. I feel it might be appropriate once this is merged to make a dev release with just this and the tests update, out of an abundance of caution.

**Comment by Leont** [comment]
Why are `META.json` and `META.yml` removed from the `MANIFEST`? They should be shipped with the distribution.

**Comment by jkeenan** [comment]
On 3/15/20 4:14 AM, Leon Timmermans wrote:
> Why are |META.json| and |META.yml| removed from the |MANIFEST|? They 
> should be shipped with the distribution.
> 

Excerpt of discussion last night on #toolchain:

(07:26:32 PM) kid51: So, as I understand it, the MANIFEST is being 
processed by Makefile.PL ...
(07:26:41 PM) leont_ left the room (quit: Ping timeout: 360 seconds).
(07:26:56 PM) kid51: ... notes absence of META.* in the repo and complains
(07:30:51 PM) kid51: The "Warning: the following files are missing in 
your kit" is misleading, as (apart from being listed in MANIFEST) 
there's no need for META.* to exist as of the time of 'perl Makefile.PL' 
-- correct?
(07:34:56 PM) Grinnz: kid51: MANIFEST within the result of 'make dist' 
will also include META.json and META.yml
(07:35:05 PM) Grinnz: there is no need for you to edit it
(07:35:40 PM) Grinnz: that is an install-time complaint, it is not a 
problem for the author
(07:36:27 PM) Grinnz: rather, the problem there is that you have META.* 
in your MANIFEST
(07:36:36 PM) Grinnz: that should be added by 'make dist', not the author
(07:37:15 PM) kid51: Yes, that's my conclusion as well.  So I'm going to 
submit a p.r. to remove META.* from distro's MANIFEST.
(07:37:54 PM) Grinnz: but the uploaded tarball should both contain 
META.json/yml, and have those in MANIFEST
(07:38:03 PM) Grinnz: and make dist takes care of that
(07:38:17 PM) kid51: I'll verify that while preparing p.r.  Thx.

As noted by Grinnz and confirmed by me in 
https://rt.cpan.org/Ticket/Display.html?id=132152#txn-1889922, META.* do 
not need to be in the MANIFEST as the latter file is found *in the 
repository*.  'make dist' will create those two files and automatically 
add them to the MANIFEST *that ships in the tarball*.

Thank you very much.
Jim Keenan

**Comment by mohawk2** [comment]
I believe that with a rebase the change to `MANIFEST` will disappear since that was already done in https://github.com/Perl-Toolchain-Gang/ExtUtils-Install/commit/48d360759996c8fea576005cdb062c0df159a60d, just leaving the (valid) `MANIFEST.SKIP` update. Could you do that rebase?

**Comment by jkeenan** [comment]
> I believe that with a rebase the change to `MANIFEST` will disappear since that was already done in [48d3607](https://github.com/Perl-Toolchain-Gang/ExtUtils-Install/commit/48d360759996c8fea576005cdb062c0df159a60d), just leaving the (valid) `MANIFEST.SKIP` update. Could you do that rebase?

I'll do so once master is stable after pending p.r. merges.

Thank you very much.
Jim Keenan

**Comment by mohawk2** [comment]
My point is that this PR will then become minimal and non-conflicting. It's up to you though!

**Pull request merged**
