### PR TITLE
Remove Test::More from t/lib

### LINKED ISSUE #24: Remove t/lib/Test from the repo?
I just noticed that t/lib includes what looks like files from Test::Simple. The changes seem to pre-date git so I can't determine the reason but I would guess that it is no longer relevant. Can anyone comment if that's the case?

### PR DESCRIPTION
**Pull request by toddr**
Resolves #24

Given Test::More is readily available on CPAN and ships with M::I
in blead it is better to rely on those updated versions than ship
our own dated version.

### CODE REVIEW

**Comment by mohawk2** [comment]
Needs to also update `MANIFEST`. Probably we need an `xt` test to catch that. cf https://github.com/graphql-perl/graphql-perl/blob/master/xt/manifest.t

**Comment by mohawk2** [comment]
@bingos also correctly points out that the `Test::More` dep needs updating to the deleted version (0.62).

**Comment by toddr** [comment]
MANIFEST and 0.62 dep added.

**Comment by bingos** [comment]
I've just tested removing the t/lib/Test and ran a build and test with perl 5.6.2 (which comes with Test::More 0.47) so I am reasonably happy having that as a minimum Test::More requirement.

**Comment by toddr** [comment]
ok should I lower the Makefile.PL requirement then?

**Pull request merged**
